config/routes.rb
Rails.application.routes.draw do
  resources :reminders
root 'reminders#index'
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  validates_presence_of :title, :description, :date, :remind_me
  validates :title, uniqueness: { message: "don't repeat your fucking titles" }
  validate :validates_date
  private
  def validates_date
    if remind_me > date
      self.errors.add(:remind_me, :invalid, message: 'are you a fucking timelord, m8?')

    end


  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    @reminder = Reminder.new(reminder_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created, ya cunt' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new, notice: "it's dead, jim" }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated, ya git' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reminder_params
      params.require(:reminder).permit(:title, :description, :date, :remind_me)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Klendar</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
  <%= csrf_meta_tags %>
  
</head>
<body>
  <div class="container">
      <h1>Reminders</h1>
    <%= yield %>
  </div>

</body>
</html>

app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class:"form-control"  %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :remind_me %><br>
    <%= f.date_select :remind_me, class:"form-control" %>
  </div><br>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing Reminder</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Date</th>
      <th>Remind me</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.title %></td>
        <td><%= reminder.description %></td>
        <td><%= l reminder.date, format: :short%></td>
        <td><%= l reminder.remind_me, format: :short%></td>
        <td>
          <div class="btn-group" role="group">
            <%= link_to 'Show', reminder, class:"btn btn-primary" %>
            <%= link_to 'Edit', edit_reminder_path(reminder), class:"btn btn-default" %>
            <%= link_to 'Destroy', reminder, {method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"} %>
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path, class:"btn btn-primary" %>

app/views/reminders/new.html.erb
<h1>New Reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', reminders_path, class:"btn btn-primary" %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @reminder.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reminder.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reminder.date %>
</p>

<p>
  <strong>Remind me:</strong>
  <%= @reminder.remind_me %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>